### PR TITLE
HELIO-3148: BAR access page

### PR DESCRIPTION
**Pull request by jgmorse**
Unable to preview this since I don't have a dev instance; so please make sure this looks okay.

### CODE REVIEW

**Comment by jmcglone** [comment]
@jgmorse 

This custom page will not display unless you also edit `app/views/e_pubs/access.html.erb` and add a case for bar on or around line 12.

You should also update your `master` branch and rebase this feature branch before resubmitting.

**Comment by gkostin1966** [comment]
The `app/views/epub/access.html.erb` page could be refactored to render the partial is it exists, otherwise render nothing.

**Comment by jgmorse** [comment]
@jmcglone Case added. I didn't endeavor to to @gkostin1966 's suggested refactoring since I can't preview it.

**Comment by gkostin1966** [comment]
I'll take over the branch, refactor, and deploy to preview.

**Comment by gkostin1966** [comment]
Pull request moved to a new branch, closing this one.

**Pull request closed without merging**
